import "./globals.scss";
import { Poppins } from "next/font/google";
// import Provider from "react-redux";

const poppins = Poppins({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <Provider> */}
      <body className={poppins.className}>{children}</body>
      {/* </Provider> */}
    </html>
  );
}
